version: '3'

output: interleaved # This shows output as it happens

tasks:
  provision:
    desc: "Bootstrap a new node: Seed key and let chezmoi build the rest"
    cmds:
      - |
        if [ -z "{{.NODE}}" ]; then
          echo "❌ Error: Specify a node. Example: task provision NODE=macmini"
          exit 1
        fi

        RAW_HOST="{{.NODE}}-raw"
        CONF_DIR=".config/chezmoi"
        
        echo "Step 1: 🔑 Authorizing MBP key..."
        ssh-copy-id -i ~/.ssh/id_ed25519.pub "${RAW_HOST}"

        echo "Step 2: 🛠 Installing chezmoi..."
        ssh "${RAW_HOST}" "mkdir -p .local/bin && curl -fsLS get.chezmoi.io/lb | sh"

        echo "Step 3: 📁 Creating config directory..."
        ssh "${RAW_HOST}" "mkdir -p ${CONF_DIR}"
        
        echo "Step 4: 🛰 Transferring ONLY the master key..."
        scp ~/.config/chezmoi/key.txt "${RAW_HOST}:${CONF_DIR}/"
        
        echo "Step 5: 🚀 Initializing (Automated/No-TTY mode)..."
        ssh "{{.NODE}}-raw" "./.local/bin/chezmoi init --apply --force --no-tty https://github.com/pdbartlett/dotfiles-chezmoi.git"
        
        echo "✅ {{.NODE}} is fully provisioned!"

  update-all:
    desc: "Attempts to run all updates"
    cmd: echo "TODO"
