version: '3'

tasks:
  provision:
    desc: "Bootstrap a new node: install chezmoi, seed keys, and init"
    cmds:
      - |
        if [ -z "{{.NODE}}" ]; then
          echo "❌ Error: Specify a node. Example: task provision NODE=macmini"
          exit 1
        fi

        RAW_HOST="{{.NODE}}-raw"
        
        echo "Step 1: 🔑 Authorizing MBP key on ${RAW_HOST}..."
        ssh-copy-id -i ~/.ssh/id_ed25519.pub "${RAW_HOST}"

        echo "Step 2: 🛠 Installing chezmoi..."
        # We use a path that doesn't rely on remote variable expansion for the install
        ssh "${RAW_HOST}" "mkdir -p .local/bin && curl -fsLS get.chezmoi.io | sh -s -- -b .local/bin"

        echo "Step 3: 📁 Creating remote config directory..."
        ssh "${RAW_HOST}" "mkdir -p .config/chezmoi"
        
        echo "Step 4: 🛰 Transferring key and config..."
        # We strip the leading $HOME/ and trailing slash. 
        # scp looks relative to the home dir by default.
        scp ~/.config/chezmoi/key.txt ~/.config/chezmoi/chezmoi.yaml "${RAW_HOST}:.config/chezmoi/"
        
        echo "Step 5: 🚀 Initializing chezmoi..."
        # We use the dot-path which is universally understood by all shells
        ssh "${RAW_HOST}" "./.local/bin/chezmoi init --apply https://github.com/pdbartlett/dotfiles-chezmoi.git"
        
        echo "✅ {{.NODE}} is fully provisioned!"
